#!/bin/bash
[ ! -d ./pyals-docker-shared ] && mkdir ./pyals-docker-shared
xhost local:docker
docker run --rm -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix -v $PWD/pyals-docker-shared:/root/shared -w /root --privileged -it pyals-docker /bin/zsh
